package hust.software.elon.domain;

import java.util.Date;

public class AuditPolicy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.name
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.tag_ids
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private String tagIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.judge_json
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private String judgeJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.description
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.create_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.create_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.update_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.update_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_policy.status
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.id
     *
     * @return the value of audit_policy.id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.id
     *
     * @param id the value for audit_policy.id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.name
     *
     * @return the value of audit_policy.name
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.name
     *
     * @param name the value for audit_policy.name
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.tag_ids
     *
     * @return the value of audit_policy.tag_ids
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.tag_ids
     *
     * @param tagIds the value for audit_policy.tag_ids
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds == null ? null : tagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.judge_json
     *
     * @return the value of audit_policy.judge_json
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public String getJudgeJson() {
        return judgeJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.judge_json
     *
     * @param judgeJson the value for audit_policy.judge_json
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setJudgeJson(String judgeJson) {
        this.judgeJson = judgeJson == null ? null : judgeJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.description
     *
     * @return the value of audit_policy.description
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.description
     *
     * @param description the value for audit_policy.description
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.create_user_id
     *
     * @return the value of audit_policy.create_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.create_user_id
     *
     * @param createUserId the value for audit_policy.create_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.create_time
     *
     * @return the value of audit_policy.create_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.create_time
     *
     * @param createTime the value for audit_policy.create_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.update_user_id
     *
     * @return the value of audit_policy.update_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.update_user_id
     *
     * @param updateUserId the value for audit_policy.update_user_id
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.update_time
     *
     * @return the value of audit_policy.update_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.update_time
     *
     * @param updateTime the value for audit_policy.update_time
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_policy.status
     *
     * @return the value of audit_policy.status
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_policy.status
     *
     * @param status the value for audit_policy.status
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}