server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: safety_audit
    url: jdbc:mysql://106.14.206.105:3306/safety_audit?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: elon
    password: Elon.12345


  redis:
    host: 106.14.206.105
    port: 6379
    database: 7
    password: long.cool

thrift:
  zkHosts: 106.14.206.105:2181
  namespace: safety_audit
  server:
    port: 40000
  connectionTimeout: 3000
  sessionTimeout: 3000

file:
  #  文件大小 /M
  fileSize: 500
  #  头像大小 /M
  iconSize: 10
  mac-root: ~/safety_audit/
  linux-root: /home/safety_audit/
  win-root: C:/safety_audit/
  user-icon: user_icon/
  audio: audio/
  other: other/


