package hust.software.elon.mapper;

import hust.software.elon.domain.TestTable;
import hust.software.elon.domain.TestTableWithBLOBs;

public interface TestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int insert(TestTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int insertSelective(TestTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    TestTableWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int updateByPrimaryKeySelective(TestTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TestTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    int updateByPrimaryKey(TestTable record);
}