package hust.software.elon.domain;

public class DisposeRouter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispose_router.id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispose_router.code
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    private Long code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispose_router.review_callback
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    private String reviewCallback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispose_router.queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    private Long queueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispose_router.virtual_queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    private String virtualQueueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispose_router.id
     *
     * @return the value of dispose_router.id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispose_router.id
     *
     * @param id the value for dispose_router.id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispose_router.code
     *
     * @return the value of dispose_router.code
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispose_router.code
     *
     * @param code the value for dispose_router.code
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispose_router.review_callback
     *
     * @return the value of dispose_router.review_callback
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public String getReviewCallback() {
        return reviewCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispose_router.review_callback
     *
     * @param reviewCallback the value for dispose_router.review_callback
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public void setReviewCallback(String reviewCallback) {
        this.reviewCallback = reviewCallback == null ? null : reviewCallback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispose_router.queue_id
     *
     * @return the value of dispose_router.queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public Long getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispose_router.queue_id
     *
     * @param queueId the value for dispose_router.queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public void setQueueId(Long queueId) {
        this.queueId = queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispose_router.virtual_queue_id
     *
     * @return the value of dispose_router.virtual_queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public String getVirtualQueueId() {
        return virtualQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispose_router.virtual_queue_id
     *
     * @param virtualQueueId the value for dispose_router.virtual_queue_id
     *
     * @mbg.generated Wed May 11 19:22:04 CST 2022
     */
    public void setVirtualQueueId(String virtualQueueId) {
        this.virtualQueueId = virtualQueueId == null ? null : virtualQueueId.trim();
    }
}