/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package hust.software.elon.safety.people.domain;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-04-27")
public enum CreateType implements org.apache.thrift.TEnum {
  ExistNotCreate(1),
  NormalCreate(2),
  ForceCreate(3);

  private final int value;

  private CreateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CreateType findByValue(int value) { 
    switch (value) {
      case 1:
        return ExistNotCreate;
      case 2:
        return NormalCreate;
      case 3:
        return ForceCreate;
      default:
        return null;
    }
  }
}
