package hust.software.elon.domain;

import java.util.Date;

public class SysFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.name
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.location
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.type
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.user_id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.status
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.update_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.id
     *
     * @return the value of sys_file.id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.id
     *
     * @param id the value for sys_file.id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.name
     *
     * @return the value of sys_file.name
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.name
     *
     * @param name the value for sys_file.name
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.location
     *
     * @return the value of sys_file.location
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.location
     *
     * @param location the value for sys_file.location
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.type
     *
     * @return the value of sys_file.type
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.type
     *
     * @param type the value for sys_file.type
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.user_id
     *
     * @return the value of sys_file.user_id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.user_id
     *
     * @param userId the value for sys_file.user_id
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.status
     *
     * @return the value of sys_file.status
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.status
     *
     * @param status the value for sys_file.status
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_time
     *
     * @return the value of sys_file.create_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_time
     *
     * @param createTime the value for sys_file.create_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.update_time
     *
     * @return the value of sys_file.update_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.update_time
     *
     * @param updateTime the value for sys_file.update_time
     *
     * @mbg.generated Sun Apr 03 20:25:25 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}