package hust.software.elon.domain;

import java.util.Date;

public class TestTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.id
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.name
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.create_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.update_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.b
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    private String b;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.id
     *
     * @return the value of test_table.id
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.id
     *
     * @param id the value for test_table.id
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.name
     *
     * @return the value of test_table.name
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.name
     *
     * @param name the value for test_table.name
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.create_time
     *
     * @return the value of test_table.create_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.create_time
     *
     * @param createTime the value for test_table.create_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.update_time
     *
     * @return the value of test_table.update_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.update_time
     *
     * @param updateTime the value for test_table.update_time
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.b
     *
     * @return the value of test_table.b
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.b
     *
     * @param b the value for test_table.b
     *
     * @mbg.generated Sun Apr 24 20:36:38 CST 2022
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }
}