package hust.software.elon.mapper;

import hust.software.elon.domain.SensitiveTable;

import java.util.List;

public interface SensitiveTableMapper {

    List<SensitiveTable> selectAllTables();

    List<SensitiveTable> selectTablesByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    int insert(SensitiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    int insertSelective(SensitiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    SensitiveTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    int updateByPrimaryKeySelective(SensitiveTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_table
     *
     * @mbg.generated Fri Apr 22 16:17:56 CST 2022
     */
    int updateByPrimaryKey(SensitiveTable record);
}