package hust.software.elon.mapper;

import hust.software.elon.domain.SensitiveWord;

public interface SensitiveWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    int insert(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    int insertSelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    SensitiveWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    int updateByPrimaryKeySelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    int updateByPrimaryKey(SensitiveWord record);
}