package hust.software.elon.mapper;

import hust.software.elon.domain.AuditTag;

import java.util.List;

public interface AuditTagMapper {

    List<AuditTag> selectByIds(List<Long> tagIds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    int insert(AuditTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    int insertSelective(AuditTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    AuditTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    int updateByPrimaryKeySelective(AuditTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_tag
     *
     * @mbg.generated Wed Apr 27 19:17:55 CST 2022
     */
    int updateByPrimaryKey(AuditTag record);
}