server:
  port: 7776
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: safety_audit
    url: jdbc:mysql://106.14.206.105:3306/safety_audit?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: elon
    password: Elon.12345

  # Kafka 配置项，对应 KafkaProperties 配置类
  kafka:
    bootstrap-servers: 106.14.206.105:9092 # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
    # Kafka Producer 配置项
    producer:
      acks: all # 0-不应答。1-leader 应答。all-所有 leader 和 follower 应答。
      retries: 3 # 发送失败时，重试发送的次数
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 消息的 value 的序列化
     # Kafka Consumer 配置项
    consumer:
      auto-offset-reset: earliest # 设置消费者分组最初的消费进度为 earliest 。可参考博客 https://blog.csdn.net/lishuangzhe7047/article/details/74530417 理解
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: hust.software.elon.entity
        isolation:
          level: read_committed # 读取已提交的消息
    # Kafka Consumer Listener 监听器配置
    listener:
      missing-topics-fatal: false # 消费监听接口监听的主题不存在时，默认会报错。所以通过设置为 false ，解决报错



  redis:
    host: 106.14.206.105
    port: 6379
    database: 7
    password: long.cool

thrift:
  zkHosts: 106.14.206.105:2181
  namespace: safety_audit
  server:
    port: 40000
  connectionTimeout: 3000
  sessionTimeout: 3000

safety:
  pipeline:
    kafka-topic: safety_audit_pipeline_x