package hust.software.elon.domain;

import java.util.Date;

public class SensitiveWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.score
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.description
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.table_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Long tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.status
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.user_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.create_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.update_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.id
     *
     * @return the value of sensitive_word.id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.id
     *
     * @param id the value for sensitive_word.id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.word
     *
     * @return the value of sensitive_word.word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.word
     *
     * @param word the value for sensitive_word.word
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.score
     *
     * @return the value of sensitive_word.score
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.score
     *
     * @param score the value for sensitive_word.score
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.description
     *
     * @return the value of sensitive_word.description
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.description
     *
     * @param description the value for sensitive_word.description
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.table_id
     *
     * @return the value of sensitive_word.table_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Long getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.table_id
     *
     * @param tableId the value for sensitive_word.table_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.status
     *
     * @return the value of sensitive_word.status
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.status
     *
     * @param status the value for sensitive_word.status
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.user_id
     *
     * @return the value of sensitive_word.user_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.user_id
     *
     * @param userId the value for sensitive_word.user_id
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.create_time
     *
     * @return the value of sensitive_word.create_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.create_time
     *
     * @param createTime the value for sensitive_word.create_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.update_time
     *
     * @return the value of sensitive_word.update_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.update_time
     *
     * @param updateTime the value for sensitive_word.update_time
     *
     * @mbg.generated Thu Apr 21 11:49:49 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}