/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package hust.software.elon.safety.model.domain;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-04-23")
public enum RiskType implements org.apache.thrift.TEnum {
  MODEL_NONE(0),
  MODEL_ASR(1),
  MODEL_SENSITIVE_WORD(2),
  MODEL_REPEAT(3),
  MODEL_VOICE_PRINT(4);

  private final int value;

  private RiskType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RiskType findByValue(int value) { 
    switch (value) {
      case 0:
        return MODEL_NONE;
      case 1:
        return MODEL_ASR;
      case 2:
        return MODEL_SENSITIVE_WORD;
      case 3:
        return MODEL_REPEAT;
      case 4:
        return MODEL_VOICE_PRINT;
      default:
        return null;
    }
  }
}
